name: tests & linting

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Run tests
      run: TESTING=1 pytest -rf test/

    - name: check linting
      run: |
        # E203 and W503 don't work well with black
        flake8 parsons/ test/ useful_resources/ --extend-ignore=E203,W503
        black --check parsons/ test/ useful_resources/
